---
title: mb bischoff
timezone: America/New_York
collections:
  category:
    title: Categories
    output: true
  formats:
    title: Formats
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
    description: ''
    format: post
    link: 
    audio:
      title: 
      link: 
    picture:
      webp_image: 
      jpeg_image: 
      png_image: 
      width: 
      height: 
      alt: 
    thanks: 
    via: 
- scope:
    path: ''
    type: category
  values:
    layout: category
description: 'mb bischoff is a designer & developer in New York City. They are a founder
  and partner at Lickability, a software studio known for its apps and work for clients
  like The Atlantic, Houseparty, and Meetup.

'
permalink: "/:title/"
url: https://mbbischoff.com
paginate: 10
baseurl: 
author:
  name: mb bischoff
  url: https://twitter.com/mb
  email: mb@mbbischoff.com
  twitter: mb
logo: "/uploads/matthew.jpeg"
version: 3
license:
  copyright: 2024 <span class="full-name">mb bischoff</span>
  url: http://creativecommons.org/licenses/by-sa/4.0/
plugins:
- jekyll-sitemap
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
- jekyll-paginate
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
repository: mattbischoff/website
header:
  title: mb
  subtitle: <a class="full-name" href="/about">mb bischoff</a> <small class="text-secondary">(<a
    class="secondary" href="https://pronouns.org/they-them">they/them</a>)</small>
    makes <a href="https://lickability.com" target="_blank"><i class="fa-brands fa-app-store-ios
    fa-sm"></i>&nbsp;apps</a>, <a href="/archive/"><i class="fa-solid fa-pen-to-square
    fa-sm"></i>&nbsp;posts</a>, & <a href="https://absolutelycrushed.com" target="_blank"><i
    class="fa-solid fa-podcast fa-sm"></i>&nbsp;podcasts</a>.<em class="smaller"><a
    class="secondary" href="/under-construction/"><i class="fa-solid fa-triangle-person-digging"></i>&nbsp;under
    construction</a></em>
navigation_links:
- title: Home
  url: "/"
  icon: fa-house
  selected_icon: fa-house
- title: About
  url: "/about/"
  icon: fa-circle-user
  selected_icon: fa-circle-user
- title: Now
  url: "/now/"
  icon: fa-clock
  selected_icon: fa-clock
- title: Archive
  url: "/archive/"
  icon: fa-archive
  selected_icon: fa-archive
- title: Contact
  url: "/contact/"
  icon: fa-comment-dots
  selected_icon: fa-comment-dots
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
tag_page_layout: tag_page
tag_page_dir: tag
tag_page_data:
  sitemap: false
tag_permalink_style: pretty
